### ISSUE TITLE
[zigpy-integration] - ZNP stack trace at plugin start

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1011]
```
2022-01-12 21:09:38,897 DEBUG   :Received command: ZDO.SimpleDescRsp.Callback(Src=0x0000, Status=<Status.SUCCESS: 0>, NWK=0x0000, SimpleDescriptor=SizePrefixedSimpleDescriptor(endpoint=1, profile=260, device_type=1024, device_version=0, input_clusters=[0, 25], output_clusters=[1280, 1282]))
2022-01-12 21:09:38,903 DEBUG   :Received command: ZDO.MsgCbIncoming.Callback(Src=0x0000, IsBroadcast=<Bool.false: 0>, ClusterId=32772, SecurityUse=0, TSN=10, MacDst=0x0000, Data=b'\x00\x00\x00\x10\x01\x04\x01\x00\x04\x00\x02\x00\x00\x19\x00\x02\x00\x05\x02\x05')
2022-01-12 21:09:38,910 DEBUG   :Received frame on uninitialized device <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=False> from ep 0 to ep 0, cluster 32772: b'\n\x00\x00\x00\x10\x01\x04\x01\x00\x04\x00\x02\x00\x00\x19\x00\x02\x00\x05\x02\x05'
2022-01-12 21:09:38,923 DEBUG   :Received frame on uninitialized device <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=False> from ep 0 to ep 0, cluster 4: b'\n\x00\x00\x01'
2022-01-12 21:09:38,927 DEBUG   : [      ZigpyCom_18] build_plugin_8002_frame_content 00124b0021600542 0 32772 0 0 b'\n\x00\x00\x00\x10\x01\x04\x01\x00\x04\x00\x02\x00\x00\x19\x00\x02\x00\x05\x02\x05' 0 0 3 2
2022-01-12 21:09:38,931 DEBUG   :[0x0000:zdo] ZDO request ZDOCmd.Simple_Desc_req: [0x0000, 1]
2022-01-12 21:09:38,935 DEBUG   :[0x0000:zdo] No handler for ZDO request:ZDOCmd.Simple_Desc_req([0x0000, 1])
2022-01-12 21:09:38,933 DEBUG   : [      ZigpyCom_18] ==> build_plugin_8002_frame_content - SourceAddr: 00124b0021600542 message: b'\n\x00\x00\x00\x10\x01\x04\x01\x00\x04\x00\x02\x00\x00\x19\x00\x02\x00\x05\x02\x05'
2022-01-12 21:09:38,941 INFO    :[0x0000:1] Discovered endpoint information: SizePrefixedSimpleDescriptor(endpoint=1, profile=260, device_type=1024, device_version=0, input_clusters=[0, 25], output_clusters=[1280, 1282])
2022-01-12 21:09:38,954 INFO    :[0x0000] Already have model and manufacturer info
2022-01-12 21:09:38,950 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000800400000300124b00216005420200000a0000001001040100040002000019000200050205, LQI: 0
2022-01-12 21:09:38,955 INFO    :[0x0000] Discovered basic device information for <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=True>
2022-01-12 21:09:38,958 DEBUG   : [ZigpyForwarder_18] ===> zdp_decoders 00124b0021600542 00 8004 0a0000001001040100040002000019000200050205
2022-01-12 21:09:38,961 DEBUG   :Device is initialized <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=True>
2022-01-12 21:09:38,964 DEBUG   : [ZigpyForwarder_18] buildframe_simple_descriptor_response - New payload 0a0000001001010404000002000000190205000502
2022-01-12 21:09:38,968 DEBUG   :Checking quirks for Texas Instruments CC1352/CC2652, Z-Stack 3.30+ (build 20210708) (00:12:4b:00:21:60:05:42)
2022-01-12 21:09:38,972 DEBUG   : [      ZigpyCom_18] build_plugin_8002_frame_content 00124b0021600542 0 4 0 0 b'\n\x00\x00\x01' 0 0 3 2
2022-01-12 21:09:38,976 INFO    :Network settings
2022-01-12 21:09:38,978 DEBUG   : [      ZigpyCom_18] ==> build_plugin_8002_frame_content - SourceAddr: 00124b0021600542 message: b'\n\x00\x00\x01'
2022-01-12 21:09:38,981 INFO    :  Model: CC1352/CC2652, Z-Stack 3.30+ (build 20210708)
2022-01-12 21:09:38,986 INFO    :  Z-Stack version: 3.3
2022-01-12 21:09:38,988 INFO    :  Z-Stack build id: 20210708
2022-01-12 21:09:38,990 INFO    :  Max concurrent requests: 1
2022-01-12 21:09:38,991 INFO    :  Channel: 15
2022-01-12 21:09:38,985 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000000400000300124b00216005420200000a000001, LQI: 0
2022-01-12 21:09:38,993 INFO    :  PAN ID: 0x3239
2022-01-12 21:09:38,997 DEBUG   : [ZigpyForwarder_18] ===> zdp_decoders 00124b0021600542 00 0004 0a000001
2022-01-12 21:09:38,999 INFO    :  Extended PAN ID: 56:78:48:45:04:01:5e:10
2022-01-12 21:09:39,004 DEBUG   : [ZigpyForwarder_18] Reception Data indication, Source Address: 00124b0021600542 Destination Address: 0000 ProfilID: 0000 ClusterID: 0004 Message Payload: 0a000001
2022-01-12 21:09:39,005 INFO    :  Device IEEE: 00:12:4b:00:21:60:05:42
2022-01-12 21:09:39,008 DEBUG   : [ZigpyForwarder_18] Decode8002 - Unknown NwkId: 00124b0021600542 Ep: 00 Cluster: 0004 Payload: 0a000001
2022-01-12 21:09:39,010 INFO    :  Device NWK: 0x0000
2022-01-12 21:09:39,015 DEBUG   :  Network key: 1d:56:18:81:7f:4f:32:ec:20:5b:ec:e5:76:53:db:12
2022-01-12 21:09:39,017 INFO    :Permitting joins for 0 seconds
2022-01-12 21:09:39,023 DEBUG   :Sending request: AF.DataRequestExt.Req(DstAddrModeAddress=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0x0000), DstEndpoint=0, DstPanId=0x0000, SrcEndpoint=0, ClusterId=54, TSN=11, Options=<TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK|ACK_REQUEST: 48>, Radius=30, Data=b'\x0B\x00\x01')
2022-01-12 21:09:39,030 DEBUG   :Starting watchdog loop
2022-01-12 21:09:39,044 DEBUG   :Received command: AF.DataRequestExt.Rsp(Status=<Status.SUCCESS: 0>)
2022-01-12 21:09:39,048 DEBUG   :Received command: ZDO.MsgCbIncoming.Callback(Src=0x0000, IsBroadcast=<Bool.false: 0>, ClusterId=54, SecurityUse=0, TSN=11, MacDst=0x0000, Data=b'\x00\x01')
2022-01-12 21:09:39,052 DEBUG   :Received command: ZDO.MgmtPermitJoinRsp.Callback(Src=0x0000, Status=<Status.SUCCESS: 0>)
2022-01-12 21:09:39,059 DEBUG   :Received command: ZDO.MsgCbIncoming.Callback(Src=0x0000, IsBroadcast=<Bool.false: 0>, ClusterId=32822, SecurityUse=0, TSN=11, MacDst=0x0000, Data=b'\x00')
2022-01-12 21:09:39,069 DEBUG   : [      ZigpyCom_18] build_plugin_8002_frame_content 00124b0021600542 0 32822 0 0 b'\x0b\x00' 0 0 3 2
2022-01-12 21:09:39,073 DEBUG   :[0x0000:zdo] ZDO request ZDOCmd.Mgmt_Permit_Joining_req: [0, <Bool.true: 1>]
2022-01-12 21:09:39,080 DEBUG   : [      ZigpyCom_18] ==> build_plugin_8002_frame_content - SourceAddr: 00124b0021600542 message: b'\x0b\x00'
2022-01-12 21:09:39,089 DEBUG   :Sending request: AF.DataRequestExt.Req(DstAddrModeAddress=AddrModeAddress(mode=<AddrMode.Broadcast: 15>, address=0xFFFC), DstEndpoint=0, DstPanId=0x0000, SrcEndpoint=0, ClusterId=54, TSN=12, Options=<TransmitOptions.NONE: 0>, Radius=0, Data=b'\x0C\x00\x00')
2022-01-12 21:09:39,096 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000803600000300124b00216005420200000b00, LQI: 0
2022-01-12 21:09:39,107 DEBUG   : [ZigpyForwarder_18] ===> zdp_decoders 00124b0021600542 00 8036 0b00
2022-01-12 21:09:39,109 DEBUG   : [ZigpyForwarder_18] Decode8014 - Permit Join status: False
2022-01-12 21:09:39,111 INFO    : [ZigpyForwarder_18] Accepting new Hardware: Disable (Off)
2022-01-12 21:09:39,113 DEBUG   : [ZigpyForwarder_18] ---> self.permitTojoin['Starttime']: 1642018179
2022-01-12 21:09:39,115 DEBUG   : [ZigpyForwarder_18] ---> self.permitTojoin['Duration']: 0
2022-01-12 21:09:39,118 DEBUG   : [ZigpyForwarder_18] ---> Current time                  : 1642018179
2022-01-12 21:09:39,120 DEBUG   : [ZigpyForwarder_18] ---> self.Ping['Permit']  (prev)   : None
2022-01-12 21:09:39,121 DEBUG   : [ZigpyForwarder_18] ---> self.Ping['Permit']  (new )   : Off
2022-01-12 21:09:39,124 DEBUG   : [ZigpyForwarder_18] ---> _to_notify                    : True
2022-01-12 21:09:39,127 DEBUG   :Received command: AF.DataRequestExt.Rsp(Status=<Status.SUCCESS: 0>)
2022-01-12 21:09:39,128 DEBUG   : [ZigpyForwarder_18] Ping - received
2022-01-12 21:09:39,154 DEBUG   : [      ZigpyCom_18] build_plugin_8002_frame_content 00124b0021600542 0 54 0 0 b'\x0b\x00\x01' 0 0 3 2
2022-01-12 21:09:39,165 DEBUG   : [      ZigpyCom_18] ==> build_plugin_8002_frame_content - SourceAddr: 00124b0021600542 message: b'\x0b\x00\x01'
2022-01-12 21:09:39,172 DEBUG   :get_device raise KeyError ieee: None nwk: 0012 !!
2022-01-12 21:09:39,176 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000003600000300124b00216005420200000b0001, LQI: 0
2022-01-12 21:09:39,183 DEBUG   : [ZigpyForwarder_18] ===> zdp_decoders 00124b0021600542 00 0036 0b0001
2022-01-12 21:09:39,193 DEBUG   : [ZigpyForwarder_18] Reception Data indication, Source Address: 00124b0021600542 Destination Address: 0000 ProfilID: 0000 ClusterID: 0036 Message Payload: 0b0001
2022-01-12 21:09:39,195 DEBUG   : [ZigpyForwarder_18] Decode8002 - Unknown NwkId: 00124b0021600542 Ep: 00 Cluster: 0036 Payload: 0b0001
2022-01-12 21:09:39,201 DEBUG   : [       MainThread] zigate_get_firmware_version
2022-01-12 21:09:39,204 DEBUG   : [      ZigpyCom_18] build_plugin_8009_frame_content 0x0000 00:12:4b:00:21:60:05:42 56:78:48:45:04:01:5e:10 12857 15
2022-01-12 21:09:39,207 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8010,  Data: 20210708, LQI: 0
2022-01-12 21:09:39,210 DEBUG   : [ZigpyForwarder_18] Decode8010 - Reception Version list:20210708 Branch: 20 Major: 21 Version: 0708
2022-01-12 21:09:39,211 INFO    : [ZigpyForwarder_18] Texas Instrument ZNP CC1352/CC2652, Z-Stack 3.30+
2022-01-12 21:09:39,215 INFO    : [ZigpyForwarder_18] Installer Version Number: 0708
2022-01-12 21:09:39,218 INFO    : [ZigpyForwarder_18] Branch Version: ==> zigpy-znp 3.x <==
2022-01-12 21:09:39,223 DEBUG   : [      ZigpyCom_18] build_plugin_8045_frame_list_controller_ep 09 <class 'str'>
2022-01-12 21:09:39,226 DEBUG   : [      ZigpyCom_18] build_plugin_8045_frame_list_controller_ep 09 000308156e0a0b0201
2022-01-12 21:09:39,231 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 3 <Endpoint id=3 in=[basic:0x0000] out=[] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,234 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8009,  Data: 000000124b002160054232395678484504015e100f, LQI: 0
2022-01-12 21:09:39,236 DEBUG   : [ZigpyForwarder_18] Decode8009: Network state - Address:0000 extaddr:00124b0021600542 PanID: 3239 Channel: 15
2022-01-12 21:09:39,239 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 8 <Endpoint id=8 in=[basic:0x0000] out=[] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,257 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 21 <Endpoint id=21 in=[basic:0x0000] out=[] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,274 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 110 <Endpoint id=110 in=[basic:0x0000] out=[] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,276 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 10 <Endpoint id=10 in=[basic:0x0000] out=[] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,279 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 11 <Endpoint id=11 in=[basic:0x0000] out=[] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,281 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 2 <Endpoint id=2 in=[basic:0x0000] out=[] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,284 DEBUG   : [      ZigpyCom_18] build_plugin_8043_frame_list_node_descriptor 1 <Endpoint id=1 in=[basic:0x0000, ota:0x0019] out=[ias_zone:0x0500, ias_wd:0x0502] status=<Status.ZDO_INIT: 1>>
2022-01-12 21:09:39,290 INFO    : [      ZigpyCom_18] zigpy_get_device( None(<class 'NoneType'>), 0012(<class 'NoneType'>)) NOT FOUND
2022-01-12 21:09:39,293 ERROR   : [      ZigpyCom_18] Error while receiving a Plugin command: ><
2022-01-12 21:09:39,314 DEBUG   :Sending request: AF.DataRequestExt.Req(DstAddrModeAddress=AddrModeAddress(mode=<AddrMode.Broadcast: 15>, address=0xFFFD), DstEndpoint=1, DstPanId=0x0000, SrcEndpoint=1, ClusterId=0, TSN=13, Options=<TransmitOptions.NONE: 0>, Radius=0, Data=b'\x14\x21\x10\x00\x05\x00\xF0\x23\x00\x00\x00\x00')
2022-01-12 21:09:39,318 ERROR   : [      ZigpyCom_18] Issue in request {'cmd': 'RAW-COMMAND', 'datas': {'Profile': 0, 'Cluster': 32770, 'TargetNwk': 18, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 1, 'payload': '01800021', 'AddressMode': 2}, 'NwkId': 18, 'TimeStamp': 1642018177.8851187, 'ACKIsDisable': False, 'Sqn': 1}, dumping stack: Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/zigpyThread.py", line 137, in worker_loop
    await dispatch_command( self, data)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/zigpyThread.py", line 250, in dispatch_command
    await process_raw_command(self, data["datas"], AckIsDisable=data["ACKIsDisable"], Sqn=data["Sqn"])
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/zigpyThread.py", line 292, in process_raw_command
    destination = self.app.get_device(nwk=t.NWK(int(NwkId,16)))
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/AppZnp.py", line 119, in get_device
    raise KeyError
KeyError
```

**Comment by pipiche38** [comment]
Quand on fait des bétises, on ne reporte des bugs
