### ISSUE TITLE
[zigpy-intergration] - crach when changing channel

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1074]
```
2022-03-08 13:22:52,516 DEBUG   : [       ZigpyCom_2] ZigyTransport: process_raw_command completed 37 NwkId: 0000 result: EmberStatus.SUCCESS msg: message send success
2022-03-08 13:22:52,520 ERROR   : [ ZigpyForwarder_2] Issue in request 0180020030ff000000803800000200000200000080000000000000000000ff03, dumping stack: Traceback (most recent call last):
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/forwarderThread.py", line 38, in forwarder_thread
    forward_message(self, message)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/instrumentation.py", line 29, in f_out
    result = f_in(self, message)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/forwarderThread.py", line 54, in forward_message
    self.F_out(message)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/plugin.py", line 813, in processFrame
    ZigateRead(self, Devices, Data)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/Modules/input.py", line 179, in ZigateRead
    _decoding(self, Devices, MsgData, MsgLQI)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/Modules/input.py", line 2539, in Decode804A
    self.networkenergy.NwkScanResponse(MsgData)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/Classes/NetworkEnergy.py", line 344, in NwkScanResponse
    MsgChannelListInterference = MsgData[22 : 22 + (2 * int(MsgScannedChannelListCount, 16))]
ValueError: invalid literal for int() with base 16: ''
```

**Comment by pipiche38** [comment]
We are receiving a Status 0x04

**Comment by pipiche38** [comment]
6eccaa87 fix
