### ISSUE TITLE
[zigpy-integration] - time to time Ezsp do not start

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1111]
Based on newradioAPI branch
```
2022-03-18 15:54:19,130 DEBUG   :Application frame 38 (getEui64) received: b'07f3a5feffcccccc'
2022-03-18 15:54:19,131 DEBUG   :Send command getConfigurationValue: (<EzspConfigId.CONFIG_SECURITY_LEVEL: 13>,)
2022-03-18 15:54:19,133 DEBUG   :Sending: b'126a21a9062a7d380c1c7e'
2022-03-18 15:54:19,140 DEBUG   :Data frame: b'226aa1a9062a15b759c73c7e'
2022-03-18 15:54:19,141 DEBUG   :Sending: b'83401b7e'
2022-03-18 15:54:19,142 DEBUG   :Application frame 82 (getConfigurationValue) received: b'000500'
2022-03-18 15:54:19,143 DEBUG   :Send command getKey: (<EmberKeyType.CURRENT_NETWORK_KEY: 3>,)
2022-03-18 15:54:19,144 DEBUG   :Sending: b'236b21a93e2a16259a7e'
2022-03-18 15:54:19,156 DEBUG   :Data frame: b'336ba1a93e2a15b15997258a4be0eddf6499309d0fedded0f2d962a9fc7e3fa7ebcdde6f8fffc7dbd5d26943787e'
2022-03-18 15:54:19,157 DEBUG   :Sending: b'8430fc7e'
2022-03-18 15:54:19,159 DEBUG   :Application frame 106 (getKey) received: b'000300036fafe1b57f96f8d71736e223b95b0f1f0120000000000000000000000000000000'
2022-03-18 15:54:19,162 DEBUG   :Send command getKey: (<EmberKeyType.TRUST_CENTER_LINK_KEY: 1>,)
2022-03-18 15:54:19,163 DEBUG   :Sending: b'346821a93e2a14e5077e'
2022-03-18 15:54:19,175 DEBUG   :Data frame: b'4468a1a93e2a15a8599537e857cea5c3c2cb9fb591bab3480df06389fc7e3fa7ebcdde687c5a3924191ea5239d7e'
2022-03-18 15:54:19,177 DEBUG   :Sending: b'8520dd7e'
2022-03-18 15:54:19,179 DEBUG   :Application frame 106 (getKey) received: b'001a00017dcdfd9b378a5e85b81e7c74d4c3f03600000000000000000007f3a5feffcccccc'
2022-03-18 15:54:19,181 DEBUG   :Send command getCurrentSecurityState: ()
2022-03-18 15:54:19,183 DEBUG   :Sending: b'456921a93d2a02b77e'
2022-03-18 15:54:19,192 DEBUG   :Data frame: b'5569a1a93d2a15465993b98054aa5e85504cfe7e'
2022-03-18 15:54:19,194 DEBUG   :Sending: b'8610be7e'
2022-03-18 15:54:19,195 DEBUG   :Application frame 105 (getCurrentSecurityState) received: b'00f40007f3a5feffcccccc'
2022-03-18 15:54:19,197 DEBUG   :Tries remaining: 3
2022-03-18 15:54:19,199 INFO    :[0x0000] Requesting 'Node Descriptor'
2022-03-18 15:54:19,201 DEBUG   :Tries remaining: 2
2022-03-18 15:54:19,201 DEBUG   :[0x0000] Extending timeout for 0x01 request
2022-03-18 15:54:19,203 DEBUG   :Extending timeout for cc:cc:cc:ff:fe:a5:f3:07/0x0000
2022-03-18 15:54:19,203 DEBUG   :Send command setExtendedTimeout: (cc:cc:cc:ff:fe:a5:f3:07, True)
2022-03-18 15:54:19,205 WARNING :Device failed to initialize due to unexpected error
Traceback (most recent call last):
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy/device.py", line 158, in initialize
    await self._initialize()
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy/util.py", line 113, in retry
    r = await func()
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy/device.py", line 183, in _initialize
    await self.get_node_descriptor()
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy/device.py", line 142, in get_node_descriptor
    status, _, node_desc = await self.zdo.Node_Desc_req(
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy/util.py", line 113, in retry
    r = await func()
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy/device.py", line 274, in request
    result, msg = await self._application.request(
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/bellows/zigbee/application.py", line 762, in request
    await self._ezsp.setExtendedTimeout(device.ieee, True)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 468, in wait_for
    await waiter
RuntimeError: Task <Task pending name='Task-1' coro=<radio_start() running at /home/domoticz/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py:140> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop
2022-03-18 15:54:19,206 DEBUG   :Sending: b'566e21a92a2a1241fc6ab5e9669993d9ee7e'
2022-03-18 15:54:19,212 DEBUG   :Starting EZSP watchdog
2022-03-18 15:54:19,213 DEBUG   :Send command getConfigurationValue: (<EzspConfigId.CONFIG_MULTICAST_TABLE_SIZE: 6>,)
2022-03-18 15:54:19,218 ERROR   :Couldn't start application
2022-03-18 15:54:19,219 DEBUG   :Cancelling watchdog
2022-03-18 15:54:19,221 DEBUG   :Closed serial connection
2022-03-18 15:54:19,229 ERROR   :exception calling callback for <Future at 0xa8b44478 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by zigbeefordomoticz** [comment]
Fixed
