### ISSUE TITLE
[Zigpy-Integration] - ZNP error message

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1141]
seen this error message in a user plugin log

```
2022-04-15 16:57:38,556 ERROR   :Received an exception while passing frame to API: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0xC0, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\x6C\x09\x80'))
ValueError: 108 is not a valid DeviceState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/uart.py", line 79, in data_received
    self._api.frame_received(frame.payload)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/api.py", line 680, in frame_received
    command = command_cls.from_frame(frame, align=self.nvram.align_structs)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/types/commands.py", line 416, in from_frame
    params[param.name], data = param.type.deserialize(data)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/types/basic.py", line 83, in deserialize
    r = cls.from_bytes(data[: cls._size], "little", signed=cls._signed)
  File "/usr/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/usr/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 108 is not a valid DeviceState
```

cc: @puddly

**Comment by pipiche38** [comment]
These is based on the zigpy dev branch
```
2022-04-16 11:50:23,504 ERROR   :Received an exception while passing frame to API: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0xC0, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\x32\x47\x80'))
ValueError: 50 is not a valid DeviceState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/uart.py", line 79, in data_received
    self._api.frame_received(frame.payload)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/api.py", line 680, in frame_received
    command = command_cls.from_frame(frame, align=self.nvram.align_structs)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/types/commands.py", line 416, in from_frame
    params[param.name], data = param.type.deserialize(data)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/zigpy_znp/types/basic.py", line 83, in deserialize
    r = cls.from_bytes(data[: cls._size], "little", signed=cls._signed)
  File "/usr/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/usr/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 50 is not a valid DeviceState
```
