### ISSUE TITLE
self.configureReporting.prepare_and_send_configure_reporting( AttributeError: 'NoneType' object has no attribute 'prepare_and_send_configure_reporting'

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1176]
Multiple errors received in the last 5 minutes:

```
2022-05-11 17:15:22.354 Error: Zigbee: forwarder_thread - Error while receiving a Coordinator command
2022-05-11 17:15:22.380 Error: Zigbee: Issue in request 0180020028ff00010402040b0b02db3c020000182f0a010030002403, dumping stack: Traceback (most recent call last): 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Classes/ZigpyTransport/forwarderThread.py", line 38, in forwarder_thread forward_message(self, message) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Classes/ZigpyTransport/instrumentation.py", line 29, in f_out result = f_in(self, message) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Classes/ZigpyTransport/forwarderThread.py", line 54, in forward_message self.F_out(message) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/plugin.py", line 901, in processFrame ZigateRead(self, Devices, Data) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/input.py", line 181, in ZigateRead _decoding(self, Devices, MsgData, MsgLQI) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/input.py", line 2971, in Decode8102 callbackDeviceAwake(self, Devices, MsgSrcAddr, MsgSrcEp, MsgClusterId) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/callback.py", line 50, in callbackDeviceAwake func(self, Devices, NwkId, endpoint, cluster) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/schneider_wiser.py", line 76, in callbackDeviceAwake_Schneider vact_config_reporting_normal(self, NwkId, EndPoint) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/schneider_wiser.py", line 1763, in vact_config_reporting_normal schneider_UpdateConfigureReporting(self, NwkId, EndPoint, "0001", AttributesConfig) 
File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/schneider_wiser.py", line 1838, in schneider_UpdateConfigureReporting self.configureReporting.prepare_and_send_configure_reporting( AttributeError: 'NoneType' object has no attribute 'prepare_and_send_configure_reporting'
```

**Comment by pipiche38** [comment]
d17b1e5a
