### ISSUE TITLE
[zigpy] - error during runtime

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1200]
On a large system ( more than 60 devices), suddenly the Elelabs seem to be stuck and plenty of error occured.

@puddly do you have any advice on how such Timeout should be handled ?

```
uture: <Task finished coro=<transport_request() done, defined at /home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py:533> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 552, in transport_request
    result, msg = await self.app.request( destination, Profile, Cluster, sEp, dEp, sequence, payload, expect_reply, use_ieee )
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/bellows/zigbee/application.py", line 581, in request
    self.direct, device.nwk, aps_frame, message_tag, data
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2022-05-29 11:27:49,653 DEBUG   :Couldn't send command sendUnicast((<EmberOutgoingMessageType.OUTGOING_DIRECT: 0>, 0x9233, EmberApsFrame(profileId=260, clusterId=6, sourceEndpoint=1, destinationEndpoint=3, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=45), 48, b'\x10\x00\x00\x00\x00')). EZSP is not running
2022-05-29 11:27:49,657 ERROR   :Task exception was never retrieved
future: <Task finished coro=<transport_request() done, defined at /home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py:533> exception=EzspError('EZSP is not running')>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 552, in transport_request
    result, msg = await self.app.request( destination, Profile, Cluster, sEp, dEp, sequence, payload, expect_reply, use_ieee )
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/bellows/zigbee/application.py", line 581, in request
    self.direct, device.nwk, aps_frame, message_tag, data
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/bellows/ezsp/__init__.py", line 137, in _command
    raise EzspError("EZSP is not running")
bellows.exception.EzspError: EZSP is not running
2022-05-29 11:27:49,660 ERROR   :Task exception was never retrieved
future: <Task finished coro=<transport_request() done, defined at /home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py:533> exception=ControllerError('ApplicationController is not running')>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 552, in transport_request
    result, msg = await self.app.request( destination, Profile, Cluster, sEp, dEp, sequence, payload, expect_reply, use_ieee )
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/bellows/zigbee/application.py", line 528, in request
    raise ControllerError("ApplicationController is not running")
bellows.exception.ControllerError: ApplicationController is not running
2022-05-29 11:27:49,663 ERROR   :Task exception was never retrieved
```

**Comment by pipiche38** [comment]
@puddly other question,  why do we get a bellows specific exception and not a zigpy one ?
