### ISSUE TITLE
[Model Certification] - AQSZB-110

### ISSUE THREAD

**Issue by filippocomparin** [sasu-drooz/Domoticz-Zigate#1539]
Brand: Frient - Develco 
Model: AQSZB-110 - Air Quality Sensor
Tecnical data: https://www.develcoproducts.com/media/1674/aqszb-110-technical-manual-air-quality-sensor-04-08-20.pdf

I tried to add this config:
```
{
    "_source": "https://github.com/zigbeefordomoticz/Domoticz-Zigbee/issues/1448",
    "_blakadder": "https://zigbee.blakadder.com/Aqara_AAQS-S01.html",
    "Ep": {
        "01": {
			"Type": ""
		},
		"26": {
			"0000": "",
			"0001": "",
			"0003": "",
			"0020": "",
			"0402": "",
			"0405": "",
			"042E": "",
			"FC03": "",
			"Type": "Temp/Humi/Voc"
		}
    },
    "Type": "",
    "ClusterToBind": [ "0402", "0405", "FC03" ],
    "ConfigureReporting": {
        "0402": { "Attributes": { "0000": { "DataType": "29", "MinInterval": "000a", "MaxInterval": "012C", "TimeOut": "0000", "Change": "0001" } } },
        "0405": { "Attributes": { "0000": { "DataType": "21", "MinInterval": "000a", "MaxInterval": "012C", "TimeOut": "0000", "Change": "0001" } } },
	"FC03": { "Attributes": { "0000": { "DataType": "21", "MinInterval": "000a", "MaxInterval": "012C", "TimeOut": "0000", "Change": "0001" } } }
    },
    "ReadAttributes": {
       	"0000": [ "0000", "0004", "0005", "0006", "0007" ],
		"0001": [ "0020" ],
        "0402": [ "0000" ],
        "0405": [ "0000" ],
		"042E": [ "0000" ],
        "FC03": [ "0000" ]
    },
    "BatteryDevice": 1,
	"VoltageConverter": 10,
	"Param": {
		"ReadAttributeChunk": 5
	}
}

```
**EDIT:**
Temperature and humidity works, but VOC is always 0.

The pairing logs:
2023-02-17 09:58:06.816 Status: Gateway: [None] NEW OBJECT: 0b2d None
2023-02-17 09:58:07.333 Status: Gateway: Device Annoucement: NwkId: 0b2d Ieee: 0015bc003600107a MacCap: 00
2023-02-17 09:58:07.697 Status: Gateway: [-] NEW OBJECT: 0b2d Active Endpoint Response Ep: 01 LQI: 138
2023-02-17 09:58:07.698 Status: Gateway: [-] NEW OBJECT: 0b2d Active Endpoint Response Ep: 26 LQI: 138
2023-02-17 09:58:07.702 Status: Gateway: [-] NEW OBJECT: 0b2d Request Simple Descriptor for Ep: 01
2023-02-17 09:58:11.153 Gateway: Assisted Pairing: Polling: ['0b2d']
2023-02-17 09:58:11.154 Gateway: --> New device: 0b2d
2023-02-17 09:58:11.154 Gateway: --> inDB , removed 0b2d from List
2023-02-17 09:58:11.154 Gateway: ----> New Ep: {'Ep': '01', 'Clusters': []}
2023-02-17 09:58:11.155 Gateway: ------> New Cluster: {'ClusterId': '0000', 'ClusterDesc': 'Basic'}
2023-02-17 09:58:11.155 Gateway: ------> New Cluster: {'ClusterId': '0001', 'ClusterDesc': 'Power Configuration'}
2023-02-17 09:58:11.155 Gateway: ------> New Cluster: {'ClusterId': '0003', 'ClusterDesc': 'Identify'}
2023-02-17 09:58:11.155 Gateway: ------> New Cluster: {'ClusterId': '0020', 'ClusterDesc': 'Poll Control'}
2023-02-17 09:58:11.156 Gateway: ------> New Cluster: {'ClusterId': '0402', 'ClusterDesc': 'Temperature Measurement'}
2023-02-17 09:58:11.156 Gateway: ------> New Cluster: {'ClusterId': '0405', 'ClusterDesc': 'Relative Humidity Measurement'}
2023-02-17 09:58:11.156 Gateway: ------> New Cluster: {'ClusterId': '042E', 'ClusterDesc': 'Unknown'}
2023-02-17 09:58:11.157 Gateway: ------> New Cluster: {'ClusterId': 'FC03', 'ClusterDesc': 'Unknown'}
2023-02-17 09:58:11.157 Gateway: ----> New Ep: {'Ep': '26', 'Clusters': [{'ClusterId': '0000', 'ClusterDesc': 'Basic'}, {'ClusterId': '0001', 'ClusterDesc': 'Power Configuration'}, {'ClusterId': '0003', 'ClusterDesc': 'Identify'}, {'ClusterId': '0020', 'ClusterDesc': 'Poll Control'}, {'ClusterId': '0402', 'ClusterDesc': 'Temperature Measurement'}, {'ClusterId': '0405', 'ClusterDesc': 'Relative Humidity Measurement'}, {'ClusterId': '042E', 'ClusterDesc': 'Unknown'}, {'ClusterId': 'FC03', 'ClusterDesc': 'Unknown'}]}
2023-02-17 09:58:11.159 Gateway: --> New Device: {'NwkId': '0b2d', 'ProvisionStatus': 'inDB', 'ProvisionStatusDesc': 'inDB', 'IEEE': '0015bc003600107a', 'ProfileId': '', 'ProfileIdDesc': 'Unknow', 'ZDeviceID': '', 'ZDeviceIDDesc': 'Unknow', 'Model': 'AQSZB-110', 'PluginCertified': 'yes', 'Ep': [{'Ep': '01', 'Clusters': []}, {'Ep': '26', 'Clusters': [{'ClusterId': '0000', 'ClusterDesc': 'Basic'}, {'ClusterId': '0001', 'ClusterDesc': 'Power Configuration'}, {'ClusterId': '0003', 'ClusterDesc': 'Identify'}, {'ClusterId': '0020', 'ClusterDesc': 'Poll Control'}, {'ClusterId': '0402', 'ClusterDesc': 'Temperature Measurement'}, {'ClusterId': '0405', 'ClusterDesc': 'Relative Humidity Measurement'}, {'ClusterId': '042E', 'ClusterDesc': 'Unknown'}, {'ClusterId': 'FC03', 'ClusterDesc': 'Unknown'}]}]}
2023-02-17 09:58:11.077 Status: Gateway: [0] NEW OBJECT: 0b2d Manufacturer Name: frient A/S
2023-02-17 09:58:11.080 Status: Gateway: [0] NEW OBJECT: 0b2d Model Name: AQSZB-110
2023-02-17 09:58:11.081 Status: Gateway: [None] NEW OBJECT: 0b2d Request Node Descriptor
2023-02-17 09:58:11.351 Status: Gateway: [-] NEW OBJECT: 0b2d Application Version 0001
2023-02-17 09:58:11.352 Status: Gateway: [-] NEW OBJECT: 0b2d Cluster IN Count: 03
2023-02-17 09:58:11.354 Status: Gateway: [-] NEW OBJECT: 0b2d ProfileID c0c9
2023-02-17 09:58:11.355 Status: Gateway: [-] NEW OBJECT: 0b2d ZDeviceID 0001
2023-02-17 09:58:11.356 Status: Gateway: [-] NEW OBJECT: 0b2d Simple Descriptor Response EP: 0x01 LQI: 141
2023-02-17 09:58:11.357 Status: Gateway: [-] NEW OBJECT: 0b2d Cluster In 1: 0003 (Identify)
2023-02-17 09:58:11.358 Status: Gateway: [-] NEW OBJECT: 0b2d Cluster In 2: 0005 (Scenes)
2023-02-17 09:58:11.359 Status: Gateway: [-] NEW OBJECT: 0b2d Cluster In 3: 0006 (On/Off)
2023-02-17 09:58:11.360 Status: Gateway: [-] NEW OBJECT: 0b2d Cluster OUT Count: 00
2023-02-17 09:58:11.079 Error: Gateway: Call to function 'onHeartbeat' failed, exception details:
2023-02-17 09:58:11.097 Error: Gateway: Traceback (most recent call last):
2023-02-17 09:58:11.097 Error: Gateway: File "C:\Domoticz\plugins\Domoticz-Zigbee\plugin.py", line 1577, in onHeartbeat
2023-02-17 09:58:11.098 Error: Gateway: _plugin.onHeartbeat()
2023-02-17 09:58:11.098 Error: Gateway: File "C:\Domoticz\plugins\Domoticz-Zigbee\plugin.py", line 966, in onHeartbeat
2023-02-17 09:58:11.098 Error: Gateway: processListOfDevices(self, Devices)
2023-02-17 09:58:11.099 Error: Gateway: File "C:\Domoticz\plugins\Domoticz-Zigbee\Modules\heartbeat.py", line 891, in processListOfDevices
2023-02-17 09:58:11.099 Error: Gateway: processNotinDBDevices(self, Devices, NWKID, status, RIA)
2023-02-17 09:58:11.099 Error: Gateway: File "C:\Domoticz\plugins\Domoticz-Zigbee\Modules\pairingProcess.py", line 116, in processNotinDBDevices
2023-02-17 09:58:11.099 Error: Gateway: interview_state_createDB(self, Devices, NWKID, RIA, status)
2023-02-17 09:58:11.100 Error: Gateway: File "C:\Domoticz\plugins\Domoticz-Zigbee\Modules\pairingProcess.py", line 339, in interview_state_createDB
2023-02-17 09:58:11.100 Error: Gateway: full_provision_device(self, Devices, NWKID, RIA, status)
2023-02-17 09:58:11.100 Error: Gateway: File "C:\Domoticz\plugins\Domoticz-Zigbee\Modules\pairingProcess.py", line 386, in full_provision_device
2023-02-17 09:58:11.101 Error: Gateway: zigbee_provision_device(self, Devices, NWKID, RIA, status)
2023-02-17 09:58:11.101 Error: Gateway: File "C:\Domoticz\plugins\Domoticz-Zigbee\Modules\pairingProcess.py", line 426, in zigbee_provision_device
2023-02-17 09:58:11.101 Error: Gateway: self.configureReporting.processConfigureReporting(NwkId=NWKID)
2023-02-17 09:58:11.101 Error: Gateway: AttributeError: 'NoneType' object has no attribute 'processConfigureReporting'
2023-02-17 09:58:12.125 Error: Gateway: Decode8000 - PacketType: 0030 TypeSqn: None sqn_app: 00 sqn_aps: None Status: [ZigBee Error Code Unknown code : 80]
2023-02-17 09:58:12.638 Error: Gateway: Decode8000 - PacketType: 0030 TypeSqn: None sqn_app: 00 sqn_aps: None Status: [ZigBee Error Code Unknown code : 80]

**Comment by pipiche38** [comment]
you might try the following to update as this is a manufacturer specific cluster/attribute

"FC03": { "Attributes": { "0000": { "ManufSpecific": "1015", "DataType": "21", "MinInterval": "000a", "MaxInterval": "012C", "TimeOut": "0000", "Change": "0001" } } }

Ideally, try to switch to the develop branche, which provided changes to make the plugin much more open.
Work is in progress, https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/HowTo_Device-Customization.md

[edit] try to use lowercase for the hexa, so it is consistent with the all plugin
 
[edit] reading the doc, it looks like by default there is a reporting in place, so might be good to not do anything
no binding on fc03 and no reporting on fc03

**Comment by filippocomparin** [comment]
Thanks for the reply.
I tried to add ManufSpecific and lowercase, but with no results.

I don't understand about the default reporting place. On logs I found only temperature and humidity (0402 cluster address 0x000 and 0x003) for that device, no VOC.

I've to develop a DevicesModules?

**Comment by pipiche38** [comment]
This is why I think moving to the 'develop' branch might be easier.

(1) as it is a customer specific cluster, the plugin doesn't handle such cluster
(2) with the develop branch and the new way to handle cluster, it is more open to add new clusters

[edit]
you might have a look to fcc0 `ZclDefinitions/fcc0.json` which is a private cluster that I have implemented. In your case, this would be `ZclDefinitions/fc03.json`




if it is easier for you , I'm available on keybase https://keybase.io/pipiche/chat

**Comment by pipiche38** [comment]
Attached is a potential config file which should be good on, develop branch

[AQSZB-110.json.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10775122/AQSZB-110.json.zip)

**Comment by pipiche38** [comment]
@filippocomparin any update ?
