### ISSUE TITLE
 AttributeError: 'WebServer' object has no attribute 'DomoticzMajor'

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1589]
> 2023-04-23 00:45:29.179 Error: Zigbee: No transport, write directive to '10.0.0.166:52432' ignored.
> 2023-04-23 00:45:48.510 Error: Zigbee: Call to function 'onMessage' failed, exception details:
> 2023-04-23 00:45:48.549 Error: Zigbee: Traceback (most recent call last):
> 2023-04-23 00:45:48.549 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/plugin.py", line 1562, in onMessage
> 2023-04-23 00:45:48.550 Error: Zigbee: _plugin.onMessage(Connection, Data)
> 2023-04-23 00:45:48.550 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/plugin.py", line 817, in onMessage
> 2023-04-23 00:45:48.550 Error: Zigbee: self.webserver.onMessage(Connection, Data)
> 2023-04-23 00:45:48.550 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/Classes/WebServer/onMessage.py", line 66, in onMessage
> 2023-04-23 00:45:48.550 Error: Zigbee: self.do_rest(Connection, Data["Verb"], D ata["Data"], parsed_query[1], parsed_query[2], parsed_query[3:])
> 2023-04-23 00:45:48.550 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/Classes/WebServer/dispatcher.py", line 116, in do_rest
> 2023-04-23 00:45:48.550 Error: Zigbee: HTTPresponse = REST_COMMANDS[command]["function"](verb, data, parameters)
> 2023-04-23 00:45:48.550 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/Classes/WebServer/rest_recreateWidget.py", line 51, in rest_recreate_widgets
> 2023-04-23 00:45:48.550 Error: Zigbee: CreateDomoDevice(self, self.Devices, nwkid)
> 2023-04-23 00:45:48.550 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/domoCreate.py", line 365, in CreateDomoDevice
> 2023-04-23 00:45:48.550 Error: Zigbee: if create_native_widget( self, Devices, NWKID, DeviceID_IEEE, Ep, t):
> 2023-04-23 00:45:48.551 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/domoCreate.py", line 521, in create_n ative_widget
> 2023-04-23 00:45:48.551 Error: Zigbee: NwkId, DeviceID_IEEE, widget_name, is_domoticz_new_blind(self)), NwkId)
> 2023-04-23 00:45:48.551 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/tools.py", line 1698, in is_domoticz_new_blind
> 2023-04-23 00:45:48.551 Error: Zigbee: return is_domoticz_above_2022_2(self)
> 2023-04-23 00:45:48.551 Error: Zigbee: File "/var/lib/domoticz/plugins/Domoticz-Zigate/Modules/tools.py", line 1692, in is_domoticz_above_2022_2
> 2023-04-23 00:45:48.551 Error: Zigbee: if self.DomoticzMajor > 2022:
> 2023-04-23 00:45:48.551 Error: Zigbee: AttributeError: 'WebServer' object has no attribute 'DomoticzMajor'

**Comment by pipiche38** [comment]
fix with 8ed250f6
