### ISSUE TITLE
disable_default_response - ValueError: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1591]
> 2023-04-23 21:51:11,515 ERROR   : [ZigpyForwarder_82] Issue in request 018002001aff00010400000101027d5b020000a403, dumping stack: Traceback (most recent call last):
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/forwarderThread.py", line 41, in forwarder_thread
>     forward_message(self, message)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/instrumentation.py", line 31, in f_out
>     result = f_in(self, message)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/forwarderThread.py", line 57, in forward_message
>     self.F_out(message)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/plugin.py", line 832, in processFrame
>     ZigateRead(self, Devices, Data)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/input.py", line 180, in ZigateRead
>     decoded_frame = decode8002_and_process( self, Data)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Zigbee/decode8002.py", line 40, in decode8002_and_process
>     frame = zcl_decoders(self, SrcNwkId, SrcEndPoint, TargetEp, ClusterId, Payload, frame)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Zigbee/zclDecoders.py", line 42, in zcl_decoders
>     default_response_disable, GlobalCommand, Sqn, ManufacturerCode, Command, Data = retreive_cmd_payload_from_8002(Payload)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/tools.py", line 1050, in retreive_cmd_payload_from_8002
>     zbee_zcl_ddr = disable_default_response(fcf)
>   File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/tools.py", line 1078, in disable_default_response
>     return (int(fcf,16) & 0x10) >> 4
> ValueError: invalid literal for int() with base 16: ''

**Comment by pipiche38** [comment]
fix in b5090b39
