### ISSUE TITLE
New error in profalux.py

### ISSUE THREAD

**Issue by LD40** [sasu-drooz/Domoticz-Zigate#1755]
After upgrade from 7.1.008 to 7.1.012 (stable7), I have errors when my scripts managing automatically my Profalux BSO run and try to reopen the blinds.
Seems to come from getTilt function.

Domoticz logs :
```
2024-07-09 17:27:00.425 Error: Zigate: Call to function 'onCommand' failed, exception details:
2024-07-09 17:27:00.428 Error: Zigate: Traceback (most recent call last):
2024-07-09 17:27:00.428 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigate/plugin.py", line 1563, in onCommand
2024-07-09 17:27:00.428 Error: Zigate: _plugin.onCommand( Unit, Command, Level, Color)
2024-07-09 17:27:00.428 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigate/plugin.py", line 801, in onCommand
2024-07-09 17:27:00.428 Error: Zigate: domoticz_command(self, Devices, DeviceID, Unit, self.IEEE2NWK[ DeviceID], Command, Level, Color)
2024-07-09 17:27:00.428 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigate/Modules/command.py", line 184, in domoticz_command
2024-07-09 17:27:00.428 Error: Zigate: handle_command_on(self, Devices, DeviceID, Unit, Level, Nwkid, EPout, DeviceType, BatteryLevel, SignalLevel, forceUpdateDev)
2024-07-09 17:27:00.428 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigate/Modules/command.py", line 572, in handle_command_on
2024-07-09 17:27:00.428 Error: Zigate: profalux_MoveToLiftAndTilt(self, Nwkid, level=255)
2024-07-09 17:27:00.428 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigate/Modules/profalux.py", line 279, in profalux_MoveToLiftAndTilt
2024-07-09 17:27:00.428 Error: Zigate: tilt = getTilt(self, nwkid)
2024-07-09 17:27:00.428 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigate/Modules/profalux.py", line 249, in getTilt
2024-07-09 17:27:00.428 Error: Zigate: tilt = int(self.ListOfDevices[nwkid]["Ep"]["01"]["fc21"]["0001"], 16)
2024-07-09 17:27:00.428 Error: Zigate: TypeError: int() can't convert non-string with explicit base
```

I solve temporarily the issue by adding str() in the int() function:
`tilt = int(str(self.ListOfDevices[nwkid]["Ep"]["01"]["fc21"]["0001"]), 16)`

But the problem is perhaps more complex...

**Comment by pipiche38** [comment]
please use the forum for that. This should be fixed on the wip-stable7-7.1.13
