### ISSUE TITLE
[zigpy-integration] - stack trace

### ISSUE THREAD

**Issue by zigbeefordomoticz** [sasu-drooz/Domoticz-Zigate#964]
```
2022-01-02 09:52:43,458 INFO    :[0x2102] Requesting 'Node Descriptor'
2022-01-02 09:52:43,465 DEBUG   :Tries remaining: 2
2022-01-02 09:52:43,467 DEBUG   :[0x2102] Extending timeout for 0x34 request
2022-01-02 09:52:43,468 DEBUG   : [      ZigpyCom_18] handle_message device 1: <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=True> Profile: 0000 Cluster: 8001 sEP: 0 dEp: 0 message: 3300609d52feff23a46002210000 lqi: 0
2022-01-02 09:52:43,470 DEBUG   :get_device raise KeyError ieee: None nwk: 2102 !!
2022-01-02 09:52:43,472 DEBUG   : [      ZigpyCom_18] handle_message device 2: 0000 Profile: 0000 Cluster: 8001 sEP: 0 dEp: 0 message: 3300609d52feff23a46002210000 lqi: 0
2022-01-02 09:52:43,474 DEBUG   :Sending request: ZDO.ExtRouteChk.Req(Dst=0x2102, RtStatus=<RouteStatus.ACTIVE: 1>, Options=<RouteOptions.NO_ROUTE_CACHE|MTO_ROUTE: 3>)
2022-01-02 09:52:43,476 DEBUG   : [      ZigpyCom_18] build_plugin_8002_frame_content 0000 0 ZDOCmd.IEEE_addr_rsp 0 0 b'\x33\x00\x60\x9D\x52\xFE\xFF\x23\xA4\x60\x02\x21\x00\x00' 0 0 2 2
2022-01-02 09:52:43,481 ERROR   :Task exception was never retrieved
future: <Task finished name='Task-271' coro=<ControllerApplication.on_zdo_relays_message() done, defined at /var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py:698> exception=AssertionError()>
Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 704, in on_zdo_relays_message
    device = await self._get_or_discover_device(nwk=msg.DstAddr)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/utils.py", line 191, in replacement
    return await tasks[key]
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 924, in _get_or_discover_device
    assert device.nwk == nwk
AssertionError
2022-01-02 09:52:43,483 DEBUG   : [      ZigpyCom_18] ==> build_plugin_8002_frame_content - SourceAddr: 0000 message: b'\x33\x00\x60\x9D\x52\xFE\xFF\x23\xA4\x60\x02\x21\x00\x00'
2022-01-02 09:52:43,489 DEBUG   : [      ZigpyCom_18] handle_message Sender: 0000 frame for plugin: 0180020036ff000000800100000200000200003300609d52feff23a460022100000003
2022-01-02 09:52:43,490 DEBUG   : [      ZigpyCom_18] get_device calling  callBackGetDevice 60a423fffe529d60 (<class 'str'>) None (<class 'NoneType'>)
2022-01-02 09:52:43,492 INFO    : [      ZigpyCom_18] zigpy_get_device( 60a423fffe529d60, None returns 2075 60a423fffe529d60 LXEK-1 1277
2022-01-02 09:52:43,494 DEBUG   : [      ZigpyCom_18] get_device <Device model=None manuf=None nwk=0x2075 ieee=60:a4:23:ff:fe:52:9d:60 is_initialized=False>
2022-01-02 09:52:43,496 DEBUG   :Received command: ZDO.ExtRouteChk.Rsp(Status=<RoutingStatus.SUCCESS: 0>)
2022-01-02 09:52:43,501 DEBUG   :Intercepted a ZDO request: dst_addr=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0x2102), dst_ep=0, src_ep=0, cluster=ZDOCmd.Node_Desc_req, sequence=52, options=TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK|ACK_REQUEST, radius=30, data=b'4\x02!'
2022-01-02 09:52:43,506 DEBUG   :Intercepted AP ZDO request ZDOCmd.Node_Desc_req({'NWKAddrOfInterest': 0x2102}) and replaced with ZDO.NodeDescReq.Req(DstAddr=0x2102, NWKAddrOfInterest=0x2102)
2022-01-02 09:52:43,512 DEBUG   :Sending request: ZDO.NodeDescReq.Req(DstAddr=0x2102, NWKAddrOfInterest=0x2102)
2022-01-02 09:52:43,527 DEBUG   :Received command: ZDO.NodeDescReq.Rsp(Status=<Status.SUCCESS: 0>)
2022-01-02 09:52:43,575 DEBUG   :Received command: ZDO.NodeDescRsp.Callback(Src=0x2102, Status=<Status.SUCCESS: 0>, NWK=0x2102, NodeDescriptor=NullableNodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4727, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False))
2022-01-02 09:52:43,583 DEBUG   :get_device raise KeyError ieee: None nwk: 2102 !!
2022-01-02 09:52:43,587 WARNING :Device failed to initialize due to unexpected error
Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy/device.py", line 149, in initialize
    await self._initialize()
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy/util.py", line 110, in retry
    r = await func()
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy/device.py", line 174, in _initialize
    await self.get_node_descriptor()
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy/device.py", line 133, in get_node_descriptor
    status, _, node_desc = await self.zdo.Node_Desc_req(
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy/util.py", line 110, in retry
    r = await func()
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy/device.py", line 265, in request
    result, msg = await self._application.request(
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 456, in request
    return await self._send_request(
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 1489, in _send_request
    response = await self._send_request_raw(
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 1332, in _send_request_raw
    return await self._send_zdo_request(
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 1304, in _send_zdo_request
    sender=self.get_device(nwk=dst_addr.address),
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/AppZnp.py", line 105, in get_device
    raise KeyError
KeyError

```

**Comment by badzz** [comment]
https://github.com/zigbeefordomoticz/Domoticz-Zigbee/pull/968
