### ISSUE TITLE
stack trace: application.py:783> exception=TypeError('%x format: an integer is required, not NoneType')

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#978]
2022-01-03 21:56:11,021 INFO    : [      ZigpyCom_18] zigpy_get_device( None, 6b9e returns 6b9e 00158d0001fe57bb
2022-01-03 21:56:11,028 ERROR   :Task exception was never retrieved
future: <Task finished name='Task-7' coro=<ControllerApplication.on_af_message() done, defined at /var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py:783> exception=TypeError('%x format: an integer is required, not NoneType')>
Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 805, in on_af_message
    self.handle_message(
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/AppZnp.py", line 131, in handle_message
    "handle_message device 1: %s Profile: %04x Cluster: %04x sEP: %s dEp: %s message: %s lqi: %s" % (
TypeError: %x format: an integer is required, not NoneType
2022-01-03 21:56:11,248 INFO    : [ZigpyForwarder_18] Texas Instrument ZNP CC1352/CC2652, Z-Stack 3.30+)
2022-01-03 21:56:11,266 INFO    : [ZigpyForwarder_18] Installer Version Number: 0400
2022-01-03 21:56:11,268 INFO    : [ZigpyForwarder_18] Branch Version: ==> zigpy <==

**Comment by pipiche38** [comment]
The crash happens at the plugin startup, not much in the log (debug was not enabled)

**Comment by pipiche38** [comment]
```
2022-01-03 22:00:49,982 DEBUG   :Received command: ZDO.SimpleDescReq.Rsp(Status=<Status.SUCCESS: 0>)
2022-01-03 22:00:49,987 DEBUG   :Received command: ZDO.SimpleDescRsp.Callback(Src=0x0000, Status=<Status.SUCCESS: 0>, NWK=0x0000, SimpleDescriptor=SizePrefixedSimpleDescriptor(endpoint=10, profile=260, device_type=2080, device_version=0, input_clusters=[0], output_clusters=[]))
2022-01-03 22:00:49,994 DEBUG   :Pretending we received a ZDO message: b'\x08\x00\x00\x00\x0A\x0A\x04\x01\x20\x08\x00\x01\x00\x00\x00'
2022-01-03 22:00:49,995 DEBUG   : [      ZigpyCom_18] AppZnp - get_device ieee:None nwk:0x0000
2022-01-03 22:00:49,996 DEBUG   :Received frame on uninitialized device <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=False> from ep 0 to ep 0, cluster ZDOCmd.Simple_Desc_rsp: b'\x08\x00\x00\x00\x0A\x0A\x04\x01\x20\x08\x00\x01\x00\x00\x00'
2022-01-03 22:00:49,998 DEBUG   : [      ZigpyCom_18] AppZnp - get_device found device: <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=False>
2022-01-03 22:00:50,013 DEBUG   :Received command: AF.IncomingMsg.Callback(GroupId=0x0000, ClusterId=2820, SrcAddr=0x6B9E, SrcEndpoint=1, DstEndpoint=1, WasBroadcast=<Bool.false: 0>, LQI=135, SecurityUse=<Bool.false: 0>, TimeStamp=377600, TSN=0, Data=b'\x18\x8D\x0A\x08\x05\x21\x1F\x00', MacSrcAddr=0x6B9E, MsgResultRadius=29)
2022-01-03 22:00:50,015 DEBUG   : [      ZigpyCom_18] handle_message device 1: <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=False> Profile: 0000 Cluster: 8004 sEP: 0 dEp: 0 message: 080000000a0a040120080001000000 lqi: 0
2022-01-03 22:00:50,019 INFO    :[0x0000:10] Discovered endpoint information: SizePrefixedSimpleDescriptor(endpoint=10, profile=260, device_type=2080, device_version=0, input_clusters=[0], output_clusters=[])
2022-01-03 22:00:50,020 DEBUG   : [      ZigpyCom_18] handle_message device 2: 00124b0021600542 Profile: 0000 Cluster: 8004 sEP: 0 dEp: 0 message: 080000000a0a040120080001000000 lqi: 0
2022-01-03 22:00:50,023 INFO    :[0x0000:11] Discovering endpoint information
2022-01-03 22:00:50,025 DEBUG   : [      ZigpyCom_18] build_plugin_8002_frame_content 00124b0021600542 0 ZDOCmd.Simple_Desc_rsp 0 0 b'\x08\x00\x00\x00\x0A\x0A\x04\x01\x20\x08\x00\x01\x00\x00\x00' 0 0 3 2
2022-01-03 22:00:50,027 DEBUG   :Tries remaining: 3
2022-01-03 22:00:50,029 DEBUG   : [      ZigpyCom_18] ==> build_plugin_8002_frame_content - SourceAddr: 00124b0021600542 message: b'\x08\x00\x00\x00\x0A\x0A\x04\x01\x20\x08\x00\x01\x00\x00\x00'
2022-01-03 22:00:50,033 DEBUG   :Intercepted a ZDO request: dst_addr=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, src_ep=0, cluster=ZDOCmd.Simple_Desc_req, sequence=9, options=TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK|ACK_REQUEST, radius=30, data=b'\t\x00\x00\x0b'
2022-01-03 22:00:50,035 DEBUG   : [      ZigpyCom_18] handle_message Sender: 00124b0021600542 frame for plugin: 0180020044ff000000800400000300124b0021600542020000080000000a0a0401200800010000000003
2022-01-03 22:00:50,038 DEBUG   :Intercepted AP ZDO request ZDOCmd.Simple_Desc_req({'NWKAddrOfInterest': 0x0000, 'EndPoint': 11}) and replaced with ZDO.SimpleDescReq.Req(DstAddr=0x0000, NWKAddrOfInterest=0x0000, Endpoint=11)
2022-01-03 22:00:50,043 DEBUG   : [      ZigpyCom_18] AppZnp - get_device ieee:None nwk:0x0000
2022-01-03 22:00:50,046 DEBUG   :Sending request: ZDO.SimpleDescReq.Req(DstAddr=0x0000, NWKAddrOfInterest=0x0000, Endpoint=11)
2022-01-03 22:00:50,048 DEBUG   : [      ZigpyCom_18] AppZnp - get_device found device: <ZNPCoordinator model='CC1352/CC2652, Z-Stack 3.30+ (build 20210708)' manuf='Texas Instruments' nwk=0x0000 ieee=00:12:4b:00:21:60:05:42 is_initialized=False>
2022-01-03 22:00:50,055 ERROR   :Task exception was never retrieved
future: <Task finished name='Task-297' coro=<ControllerApplication.on_af_message() done, defined at /var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py:783> exception=TypeError('%x format: an integer is required, not NoneType')>
Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/zigbee/application.py", line 805, in on_af_message
    self.handle_message(
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/AppZnp.py", line 131, in handle_message
    "handle_message device 1: %s Profile: %04x Cluster: %04x sEP: %s dEp: %s message: %s lqi: %s" % (
TypeError: %x format: an integer is required, not NoneType
```
