### ISSUE TITLE
[zigpy-integration] - zigate

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#992]
```
Jan 07 12:30:44 rasp domoticz[964]: 2022-01-07 12:30:44.452  Status: Zigpy: ===> channel: 15
Jan 07 12:30:44 rasp domoticz[964]: 2022-01-07 12:30:44.460  Status: Zigpy: ===> extendedPanId: 0x5678484504015E10
Jan 07 12:30:44 rasp domoticz[964]: 2022-01-07 12:30:44.464  Status: Zigpy: ZigpyTransport: thread_processing_and_sending Thread start.
Jan 07 12:30:44 rasp domoticz[964]: 2022-01-07 12:30:44.483  Status: Zigpy: Start Web Server connection
Jan 07 12:30:44 rasp domoticz[964]: 2022-01-07 12:30:44.485  Status: Zigpy: Web backend for Web User Interface started on port: 9440
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.001  Zigpy: Zigate receive message processing time Max: 1 ms with an of average: 1 ms
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.022  Status: Zigpy: Installer Version Number: 0320
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.026  Status: Zigpy: Branch Version: ==> zigpy-znp <==
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.034  Status: Zigpy: Initialize Zigate Data Structure 0000 00158d0004ff9109
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.057  Status: Zigpy: Updating Channel in Plugin Configuration from: 15 to: 11
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.062  Zigpy: is_domoticz_db_available: Fashion: True , Major: 2021, Minor: 1
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.062  Zigpy: is_domoticz_db_available: True
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.064  Zigpy: Zigate receive message processing time Max: 61 ms with an of average: 31 ms
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.072  Status: Zigpy: Zigate addresses ieee: 00158d0004ff9109 , short addr: 0000
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.074  Status: Zigpy: Network state UP, PANID: c511 extPANID: 0x1984484504015e10 Channel: 11
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.230  Error: Zigpy: forwarder_thread - Error while receiving a ZiGate command
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.343  Error: Zigpy: Issue in request 0180020030ff000000800400000300158d0004ff910902000001820000000003, dumping stack: Traceback (most recent call last):
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 31, in forwarder_thread
Jan 07 12:30:45 rasp domoticz[964]:     forward_message(self, message)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/instrumentation.py", line 13, in f_out
Jan 07 12:30:45 rasp domoticz[964]:     result = f_in(self, message)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 47, in forward_message
Jan 07 12:30:45 rasp domoticz[964]:     self.F_out(message)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/plugin.py", line 743, in processFrame
Jan 07 12:30:45 rasp domoticz[964]:     ZigateRead(self, Devices, Data)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 171, in ZigateRead
Jan 07 12:30:45 rasp domoticz[964]:     decoded_frame = decode8002_and_process( self, Data)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/decode8002.py", line 24, in decode8002_and_process
Jan 07 12:30:45 rasp domoticz[964]:     frame = zdp_decoders(self, SrcNwkId, SrcEndPoint, TargetEp, ClusterId, Payload, frame)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/zdpDecoders.py", line 56, in zdp_decoders
Jan 07 12:30:45 rasp domoticz[964]:     return buildframe_simple_descriptor_response(self, SrcNwkId, SrcEndPoint, ClusterId, Payload, frame)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/zdpDecoders.py", line 186, in buildframe_simple_descriptor_response
Jan 07 12:30:45 rasp domoticz[964]:     self.log.logging("zdpDecoder", "Error", "buildframe_simple_descriptor_response - not a Simple Descriptor resp" % (Payload))
Jan 07 12:30:45 rasp domoticz[964]: TypeError: not all arguments converted during string formatting
Jan 07 12:30:45 rasp domoticz[964]:
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.398  Error: Zigpy: forwarder_thread - Error while receiving a ZiGate command
Jan 07 12:30:45 rasp domoticz[964]: 2022-01-07 12:30:45.440  Error: Zigpy: Issue in request 0180020030ff000000800400000300158d0004ff910902000018820b00000003, dumping stack: Traceback (most recent call last):
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 31, in forwarder_thread
Jan 07 12:30:45 rasp domoticz[964]:     forward_message(self, message)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/instrumentation.py", line 13, in f_out
Jan 07 12:30:45 rasp domoticz[964]:     result = f_in(self, message)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 47, in forward_message
Jan 07 12:30:45 rasp domoticz[964]:     self.F_out(message)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/plugin.py", line 743, in processFrame
Jan 07 12:30:45 rasp domoticz[964]:     ZigateRead(self, Devices, Data)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 171, in ZigateRead
Jan 07 12:30:45 rasp domoticz[964]:     decoded_frame = decode8002_and_process( self, Data)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/decode8002.py", line 24, in decode8002_and_process
Jan 07 12:30:45 rasp domoticz[964]:     frame = zdp_decoders(self, SrcNwkId, SrcEndPoint, TargetEp, ClusterId, Payload, frame)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/zdpDecoders.py", line 56, in zdp_decoders
Jan 07 12:30:45 rasp domoticz[964]:     return buildframe_simple_descriptor_response(self, SrcNwkId, SrcEndPoint, ClusterId, Payload, frame)
Jan 07 12:30:45 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/zdpDecoders.py", line 186, in buildframe_simple_descriptor_response
Jan 07 12:30:45 rasp domoticz[964]:     self.log.logging("zdpDecoder", "Error", "buildframe_simple_descriptor_response - not a Simple Descriptor resp" % (Payload))
Jan 07 12:30:45 rasp domoticz[964]: TypeError: not all arguments converted during string formatting
Jan 07 12:30:45 rasp domoticz[964]:
Jan 07 12:30:52 rasp domoticz[964]: 2022-01-07 12:30:52.519  Error: Zigpy: forwarder_thread - Error while receiving a ZiGate command
Jan 07 12:30:52 rasp domoticz[964]: 2022-01-07 12:30:52.581  Error: Zigpy: Issue in request 0180020048ff000000800200000300158d0004ff91090200000100000000408f47117f0000412c0000000003, dumping stack: Traceback (most recent call last):
Jan 07 12:30:52 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 31, in forwarder_thread
Jan 07 12:30:52 rasp domoticz[964]:     forward_message(self, message)
Jan 07 12:30:52 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/instrumentation.py", line 13, in f_out
Jan 07 12:30:52 rasp domoticz[964]:     result = f_in(self, message)
Jan 07 12:30:52 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 47, in forward_message
Jan 07 12:30:52 rasp domoticz[964]:     self.F_out(message)
Jan 07 12:30:52 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/plugin.py", line 743, in processFrame
Jan 07 12:30:52 rasp domoticz[964]:     ZigateRead(self, Devices, Data)
Jan 07 12:30:52 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 178, in ZigateRead
Jan 07 12:30:52 rasp domoticz[964]:     _decoding(self, Devices, MsgData, MsgLQI)
Jan 07 12:30:52 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 1879, in Decode8042
Jan 07 12:30:52 rasp domoticz[964]:     if self.ListOfDevices[addr]["Status"] != "inDB":
Jan 07 12:30:52 rasp domoticz[964]: KeyError: 'Status'
Jan 07 12:30:52 rasp domoticz[964]:
Jan 07 12:30:52 rasp domoticz[964]: 2022-01-07 12:30:52.647  Error: Zigpy: buildframe_node_descriptor_response not a Node Descriptor frame 18000b0000

```

**Comment by pipiche38** [comment]
266d843c fix issue the 1st issue. However we were receiving an incomplete buildframe_simple_descriptor_response

**Comment by pipiche38** [comment]
close until we duplicate
