### ISSUE TITLE
[zigpy-integration] - zigate  stack trace

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#993]
```
2022-01-07 12:31:56,939 DEBUG   :[0x0000:zdo] ZDO request ZDOCmd.Simple_Desc_rsp: [<Status.SUCCESS: 0>, 0x0000, None]
2022-01-07 12:31:56,941 DEBUG   :[0x0000:zdo] No handler for ZDO request:ZDOCmd.Simple_Desc_rsp([<Status.SUCCESS: 0>, 0x0000, None])
2022-01-07 12:31:56,952 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000800400000300158d0004ff91090200001c0000000b0e00, LQI: 0
2022-01-07 12:31:56,954 DEBUG   :command : Got status for 0x0530 : sqn:14
2022-01-07 12:31:56,957 ERROR   : [ZigpyForwarder_18] forwarder_thread - Error while receiving a ZiGate command
2022-01-07 12:31:56,964 DEBUG   :command : Wait for ack for command 0x0530 sqn:14
2022-01-07 12:31:56,973 DEBUG   :Tries remaining: 1
2022-01-07 12:31:56,986 DEBUG   :[0x0000] Extending timeout for 0x08 request
2022-01-07 12:31:56,995 DEBUG   :request (0x0000, 0, <ZDOCmd.Node_Desc_req: 0x0002>, 0, 0, 8, b'\x08\x00\x00', True, False, 2, True)
2022-01-07 12:31:57,004 DEBUG   :command :cmd=0x0530  wait_status=True wait_for_datasent=False wait_for_ack=True
2022-01-07 12:31:57,022 ERROR   : [ZigpyForwarder_18] Issue in request 0180020034ff000000800400000300158d0004ff91090200001c0000000b0e000003, dumping stack: Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 31, in forwarder_thread
    forward_message(self, message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/instrumentation.py", line 13, in f_out
    result = f_in(self, message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 47, in forward_message
    self.F_out(message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/plugin.py", line 743, in processFrame
    ZigateRead(self, Devices, Data)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 171, in ZigateRead
    decoded_frame = decode8002_and_process( self, Data)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/decode8002.py", line 24, in decode8002_and_process
    frame = zdp_decoders(self, SrcNwkId, SrcEndPoint, TargetEp, ClusterId, Payload, frame)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/zdpDecoders.py", line 56, in zdp_decoders
    return buildframe_simple_descriptor_response(self, SrcNwkId, SrcEndPoint, ClusterId, Payload, frame)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Zigbee/zdpDecoders.py", line 198, in buildframe_simple_descriptor_response
    deviceId = "%04x" % struct.unpack("H", struct.pack(">H", int(SimpleDescriptor[6:10], 16)))[0]
ValueError: invalid literal for int() with base 16: ''

2022-01-07 12:32:03,977 DEBUG   :Send: 0x0530 b'020000000000020000000003080000'
```

**Comment by pipiche38** [comment]
2022-01-07 12:33:01,254 DEBUG   :Send: 0x0530 b'0200000000000200000000030c0000'
2022-01-07 12:33:01,257 DEBUG   :Frame to send: b'\x050\x00\x0f5\x02\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x03\x0c\x00\x00'
2022-01-07 12:33:01,259 DEBUG   :Frame escaped: b'\x02\x150\x02\x10\x02\x1f5\x02\x12\x02\x10\x02\x10\x02\x10\x02\x10\x02\x10\x02\x12\x02\x10\x02\x10\x02\x10\x02\x10\x02\x13\x02\x1c\x02\x10\x02\x10'
2022-01-07 12:33:01,261 DEBUG   :command : Wait for status to command 0x0530
2022-01-07 12:33:01,319 DEBUG   :Frame received: 80000009bc002905300129010000
2022-01-07 12:33:01,320 DEBUG   :data received 0x8000 b'0029053001290100' LQI:0
2022-01-07 12:33:01,322 DEBUG   :data_received : status received 0x8000 status:0x00 cmd:0x0530 sqn:41
2022-01-07 12:33:01,324 DEBUG   :zigate_callback_handler [0, 41, 1328, 1, 41, b'\x01\x00']
2022-01-07 12:33:01,327 DEBUG   :Frame received: 8002001f98000000800200000200000200000c00000000408f47117f0000412c00000000
2022-01-07 12:33:01,328 DEBUG   :data received 0x8002 b'000000800200000200000200000c00000000408f47117f0000412c000000' LQI:0
2022-01-07 12:33:01,331 DEBUG   :zigate_callback_handler [0, 0, 32770, 0, 0, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, b'\x0c\x00\x00\x00\x00@\x8fG\x11\x7f\x00\x00A,\x00\x00\x00']
2022-01-07 12:33:01,334 DEBUG   :Received frame on uninitialized device <ZiGateDevice model='ZiGate USB-TTL 3.20' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:04:ff:91:09 is_initialized=False> from ep 0 to ep 0, cluster 32770: b'\x0c\x00\x00\x00\x00@\x8fG\x11\x7f\x00\x00A,\x00\x00\x00'
2022-01-07 12:33:01,345 DEBUG   :Frame received: 800200150a00000080020000020000020000140000000b000000
2022-01-07 12:33:01,353 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000800200000300158d0004ff91090200000c00000000408f47117f0000412c000000, LQI: 0
2022-01-07 12:33:01,355 DEBUG   :data received 0x8002 b'00000080020000020000020000140000000b0000' LQI:0
2022-01-07 12:33:01,360 DEBUG   : [ZigpyForwarder_18] Decode8042 - Reception Node Descriptor for: 0000 SEQ: 0c Status: 00 manufacturer:1147 mac_capability: 8f bit_field: 4000
2022-01-07 12:33:01,362 DEBUG   :zigate_callback_handler [0, 0, 32770, 0, 0, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, b'\x14\x00\x00\x00\x0b\x00\x00']
2022-01-07 12:33:01,364 DEBUG   : [ZigpyForwarder_18] Decode8042 - Alternate PAN Coordinator = 1
2022-01-07 12:33:01,367 DEBUG   :Received frame on uninitialized device <ZiGateDevice model='ZiGate USB-TTL 3.20' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:04:ff:91:09 is_initialized=False> from ep 0 to ep 0, cluster 32770: b'\x14\x00\x00\x00\x0b\x00\x00'
2022-01-07 12:33:01,369 DEBUG   : [ZigpyForwarder_18] Decode8042 - Receiver on Idle = On
2022-01-07 12:33:01,376 DEBUG   :[0x0000:zdo] ZDO request ZDOCmd.Node_Desc_rsp: [<Status.SUCCESS: 0>, 0x0000, None]
2022-01-07 12:33:01,378 DEBUG   : [ZigpyForwarder_18] Decode8042 - Power Source = Main
2022-01-07 12:33:01,380 DEBUG   :[0x0000:zdo] No handler for ZDO request:ZDOCmd.Node_Desc_rsp([<Status.SUCCESS: 0>, 0x0000, None])
2022-01-07 12:33:01,383 DEBUG   : [ZigpyForwarder_18] Decode8042 - Device type  = FFD
2022-01-07 12:33:01,390 DEBUG   :command : Got status for 0x0530 : sqn:41
2022-01-07 12:33:01,393 DEBUG   : [ZigpyForwarder_18] Decode8042 - bit_fieldL  = 0 bit_fieldH = 64
2022-01-07 12:33:01,395 DEBUG   :command : Wait for ack for command 0x0530 sqn:41
2022-01-07 12:33:01,398 DEBUG   : [ZigpyForwarder_18] Decode8042 - bit_field = 0: 64
2022-01-07 12:33:01,402 DEBUG   : [ZigpyForwarder_18] Decode8042 - Logical Type = Coordinator
2022-01-07 12:33:01,404 ERROR   : [ZigpyForwarder_18] forwarder_thread - Error while receiving a ZiGate command
2022-01-07 12:33:01,453 ERROR   : [ZigpyForwarder_18] Issue in request 0180020048ff000000800200000300158d0004ff91090200000c00000000408f47117f0000412c0000000003, dumping stack: Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 31, in forwarder_thread
    forward_message(self, message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/instrumentation.py", line 13, in f_out
    result = f_in(self, message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 47, in forward_message
    self.F_out(message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/plugin.py", line 743, in processFrame
    ZigateRead(self, Devices, Data)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 178, in ZigateRead
    _decoding(self, Devices, MsgData, MsgLQI)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 1879, in Decode8042
    if self.ListOfDevices[addr]["Status"] != "inDB":
KeyError: 'Status'

2022-01-07 12:33:01,507 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000800200000300158d0004ff9109020000140000000b0000, LQI: 0
2022-01-07 12:33:01,510 ERROR   : [ZigpyForwarder_18] buildframe_node_descriptor_response not a Node Descriptor frame 140000000b0000
2022-01-07 12:33:01,558 DEBUG   : [ZigpyForwarder_18] Reception Data indication, Source Address: 00158d0004ff9109 Destination Address: 0000 ProfilID: 0000 ClusterID: 8002 Message Payload: 140000000b0000
2022-01-07 12:33:01,560 DEBUG   : [ZigpyForwarder_18] Decode8002 - Unknown NwkId: 00158d0004ff9109 Ep: 00 Cluster: 8002 Payload: 140000000b0000
2022-01-07 12:33:01,760 DEBUG   :request (0x0000, 0, 4, 0, 0, 9, b'\t\x00\x00\xf2', True, False, 2, True)
2022-01-07 12:33:01,763 INFO    : [      ZigpyCom_18] process_raw_command (zigpyThread) spend more than 1s (14281 ms) frame: {'cmd': 'RAW-COMMAND', 'datas': {'Profile': 0, 'Cluster': 4, 'TargetNwk': 0, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 8, 'payload': '08000008', 'AddressMode': 2}, 'NwkId': 0, 'TimeStamp': 1641555059.6328754, 'ACKIsDisable': False, 'Sqn': 8}
2022-01-07 12:33:01,764 DEBUG   :command :cmd=0x0530  wait_status=True wait_for_datasent=False wait_for_ack=True

**Comment by pipiche38** [comment]
```
2022-01-07 12:31:43,123 DEBUG   :[0x0000] Extending timeout for 0x07 request
2022-01-07 12:31:43,125 DEBUG   :request (0x0000, 0, <ZDOCmd.Node_Desc_req: 0x0002>, 0, 0, 7, b'\x07\x00\x00', True, False, 2, True)
2022-01-07 12:31:43,126 DEBUG   :command :cmd=0x0530  wait_status=True wait_for_datasent=False wait_for_ack=True
2022-01-07 12:31:49,679 DEBUG   :Send: 0x0530 b'020000000000020000000003070000'
2022-01-07 12:31:49,681 DEBUG   :Frame to send: b'\x050\x00\x0f>\x02\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x03\x07\x00\x00'
2022-01-07 12:31:49,683 DEBUG   :Frame escaped: b'\x02\x150\x02\x10\x02\x1f>\x02\x12\x02\x10\x02\x10\x02\x10\x02\x10\x02\x10\x02\x12\x02\x10\x02\x10\x02\x10\x02\x10\x02\x13\x02\x17\x02\x10\x02\x10'
2022-01-07 12:31:49,684 DEBUG   :command : Wait for status to command 0x0530
2022-01-07 12:31:49,743 DEBUG   :Frame received: 80000009bc000b0530010b010000
2022-01-07 12:31:49,744 DEBUG   :data received 0x8000 b'000b0530010b0100' LQI:0
2022-01-07 12:31:49,746 DEBUG   :data_received : status received 0x8000 status:0x00 cmd:0x0530 sqn:11
2022-01-07 12:31:49,747 DEBUG   :zigate_callback_handler [0, 11, 1328, 1, 11, b'\x01\x00']
2022-01-07 12:31:49,748 DEBUG   :Frame received: 8002001f93000000800200000200000200000700000000408f47117f0000412c00000000
2022-01-07 12:31:49,750 DEBUG   :data received 0x8002 b'000000800200000200000200000700000000408f47117f0000412c000000' LQI:0
2022-01-07 12:31:49,752 DEBUG   :zigate_callback_handler [0, 0, 32770, 0, 0, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, b'\x07\x00\x00\x00\x00@\x8fG\x11\x7f\x00\x00A,\x00\x00\x00']
2022-01-07 12:31:49,755 DEBUG   :Received frame on uninitialized device <ZiGateDevice model='ZiGate USB-TTL 3.20' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:04:ff:91:09 is_initialized=False> from ep 0 to ep 0, cluster 32770: b'\x07\x00\x00\x00\x00@\x8fG\x11\x7f\x00\x00A,\x00\x00\x00'
2022-01-07 12:31:49,764 DEBUG   :Frame received: 8002001502000000800200000200000200001c0000000b000000
2022-01-07 12:31:49,772 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8002,  Data: 000000800200000300158d0004ff91090200000700000000408f47117f0000412c000000, LQI: 0
2022-01-07 12:31:49,773 DEBUG   :data received 0x8002 b'000000800200000200000200001c0000000b0000' LQI:0
2022-01-07 12:31:49,779 DEBUG   : [ZigpyForwarder_18] Decode8042 - Reception Node Descriptor for: 0000 SEQ: 07 Status: 00 manufacturer:1147 mac_capability: 8f bit_field: 4000
2022-01-07 12:31:49,782 DEBUG   :zigate_callback_handler [0, 0, 32770, 0, 0, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, <Address address_mode=ADDRESS_MODE.NWK address=0x0000>, b'\x1c\x00\x00\x00\x0b\x00\x00']
2022-01-07 12:31:49,785 DEBUG   : [ZigpyForwarder_18] Decode8042 - Alternate PAN Coordinator = 1
2022-01-07 12:31:49,788 DEBUG   :Received frame on uninitialized device <ZiGateDevice model='ZiGate USB-TTL 3.20' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:04:ff:91:09 is_initialized=False> from ep 0 to ep 0, cluster 32770: b'\x1c\x00\x00\x00\x0b\x00\x00'
2022-01-07 12:31:49,790 DEBUG   : [ZigpyForwarder_18] Decode8042 - Receiver on Idle = On
2022-01-07 12:31:49,795 DEBUG   :[0x0000:zdo] ZDO request ZDOCmd.Node_Desc_rsp: [<Status.SUCCESS: 0>, 0x0000, None]
2022-01-07 12:31:49,797 DEBUG   : [ZigpyForwarder_18] Decode8042 - Power Source = Main
2022-01-07 12:31:49,799 DEBUG   :[0x0000:zdo] No handler for ZDO request:ZDOCmd.Node_Desc_rsp([<Status.SUCCESS: 0>, 0x0000, None])
2022-01-07 12:31:49,801 DEBUG   : [ZigpyForwarder_18] Decode8042 - Device type  = FFD
2022-01-07 12:31:49,809 DEBUG   :command : Got status for 0x0530 : sqn:11
2022-01-07 12:31:49,812 DEBUG   : [ZigpyForwarder_18] Decode8042 - bit_fieldL  = 0 bit_fieldH = 64
2022-01-07 12:31:49,813 DEBUG   :command : Wait for ack for command 0x0530 sqn:11
2022-01-07 12:31:49,815 DEBUG   : [ZigpyForwarder_18] Decode8042 - bit_field = 0: 64
2022-01-07 12:31:49,818 DEBUG   : [ZigpyForwarder_18] Decode8042 - Logical Type = Coordinator
2022-01-07 12:31:49,820 ERROR   : [ZigpyForwarder_18] forwarder_thread - Error while receiving a ZiGate command
2022-01-07 12:31:49,871 ERROR   : [ZigpyForwarder_18] Issue in request 0180020048ff000000800200000300158d0004ff91090200000700000000408f47117f0000412c0000000003, dumping stack: Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 31, in forwarder_thread
    forward_message(self, message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/instrumentation.py", line 13, in f_out
    result = f_in(self, message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 47, in forward_message
    self.F_out(message)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/plugin.py", line 743, in processFrame
    ZigateRead(self, Devices, Data)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 178, in ZigateRead
    _decoding(self, Devices, MsgData, MsgLQI)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 1879, in Decode8042
    if self.ListOfDevices[addr]["Status"] != "inDB":
KeyError: 'Status'
```

**Comment by pipiche38** [comment]
The message receive doesn't look as a Simple Descriptor  Response where we should have also the list of Cluster

**Comment by pipiche38** [comment]
make sure that debugTransportPluginEncoder is enabled

**Comment by pipiche38** [comment]
close until it is duplicated
