### ISSUE TITLE
[zigpy - integration ] - stack trace znp

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#995]
```
2022-01-07 13:53:42,414 DEBUG   :[0x4dff] Scheduling initialization
2022-01-07 13:53:42,416 DEBUG   : [ZigpyForwarder_18] Decode8009: Network state - Address:0000 extaddr:00124b0021600542 PanID: 3239 Channel: 15
2022-01-07 13:53:42,418 DEBUG   :Starting watchdog loop
2022-01-07 13:53:42,429 INFO    : [ZigpyForwarder_18] zdp_simple_descriptor_request 0000
2022-01-07 13:53:42,431 DEBUG   :Tries remaining: 3
2022-01-07 13:53:42,441 INFO    : [ZigpyForwarder_18] zdp_raw_active_endpoint_request  - [00] 0000 Queue Length: 0
2022-01-07 13:53:42,464 INFO    :[0x4dff] Requesting 'Node Descriptor'
2022-01-07 13:53:42,474 INFO    : [ZigpyForwarder_18] sendData       - [0] RAW-COMMAND {'Profile': 0, 'Cluster': 5, 'TargetNwk': 0, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 0, 'payload': '000000', 'AddressMode': 2} 0 Queue Length: 0
2022-01-07 13:53:42,475 DEBUG   :Tries remaining: 2
2022-01-07 13:53:42,479 INFO    : [      ZigpyCom_18] zigpy_get_device( 00124b000425e9ad, None returns 4dff 00124b000425e9ad
2022-01-07 13:53:42,480 DEBUG   :[0x4dff] Extending timeout for 0x0c request
2022-01-07 13:53:42,484 INFO    : [ZigpyForwarder_18] Zigate addresses ieee: 00124b0021600542 , short addr: 0000
2022-01-07 13:53:42,488 DEBUG   :Sending request: ZDO.ExtRouteChk.Req(Dst=0x4DFF, RtStatus=<RouteStatus.ACTIVE: 1>, Options=<RouteOptions.NO_ROUTE_CACHE|MTO_ROUTE: 3>)
2022-01-07 13:53:42,495 INFO    : [ZigpyForwarder_18] Network state UP, PANID: 3239 extPANID: 0x5678484504015e10 Channel: 15
2022-01-07 13:53:42,505 DEBUG   :Intercepted a ZDO request: dst_addr=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, src_ep=0, cluster=4, sequence=1, options=TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK|ACK_REQUEST, radius=30, data=b'\x01\x00\x00\x00'
2022-01-07 13:53:42,509 DEBUG   : [ZigpyForwarder_18] ZigateRead - MsgType: 8045,  Data: 0000000009000308156e0a0b0201, LQI: 0
2022-01-07 13:53:42,512 DEBUG   :Intercepted AP ZDO request 4({'NWKAddrOfInterest': 0x0000, 'EndPoint': 0}) and replaced with ZDO.SimpleDescReq.Req(DstAddr=0x0000, NWKAddrOfInterest=0x0000, Endpoint=0)
2022-01-07 13:53:42,515 INFO    : [ZigpyForwarder_18] zdp_active_endpoint_request 0000 00
2022-01-07 13:53:42,520 DEBUG   :Received command: ZDO.ExtRouteChk.Rsp(Status=<RoutingStatus.SUCCESS: 0>)
2022-01-07 13:53:42,524 INFO    : [ZigpyForwarder_18] zdp_raw_simple_descriptor_request  - [01] 0000 00 Queue Length: 1
2022-01-07 13:53:42,527 DEBUG   :Intercepted a ZDO request: dst_addr=AddrModeAddress(mode=<AddrMode.NWK: 2>, address=0x4DFF), dst_ep=0, src_ep=0, cluster=ZDOCmd.Node_Desc_req, sequence=12, options=TransmitOptions.SUPPRESS_ROUTE_DISC_NETWORK|ACK_REQUEST, radius=30, data=b'\x0c\xffM'
2022-01-07 13:53:42,529 INFO    : [ZigpyForwarder_18] sendData       - [1] RAW-COMMAND {'Profile': 0, 'Cluster': 4, 'TargetNwk': 0, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 1, 'payload': '01000000', 'AddressMode': 2} 0 Queue Length: 1
2022-01-07 13:53:42,532 DEBUG   :Intercepted AP ZDO request ZDOCmd.Node_Desc_req({'NWKAddrOfInterest': 0x4DFF}) and replaced with ZDO.NodeDescReq.Req(DstAddr=0x4DFF, NWKAddrOfInterest=0x4DFF)
2022-01-07 13:53:42,534 INFO    : [ZigpyForwarder_18] zdp_active_endpoint_request 0000 03
2022-01-07 13:53:42,537 DEBUG   :Sending request: ZDO.ExtRouteDisc.Req(Dst=0x4DFF, Options=<RouteDiscoveryOptions.UNICAST: 0>, Radius=30)
2022-01-07 13:53:42,540 INFO    : [ZigpyForwarder_18] zdp_raw_simple_descriptor_request  - [02] 0000 03 Queue Length: 2
2022-01-07 13:53:42,546 INFO    : [ZigpyForwarder_18] sendData       - [2] RAW-COMMAND {'Profile': 0, 'Cluster': 4, 'TargetNwk': 0, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 2, 'payload': '02000003', 'AddressMode': 2} 0 Queue Length: 2
2022-01-07 13:53:42,548 INFO    : [ZigpyForwarder_18] zdp_active_endpoint_request 0000 08
2022-01-07 13:53:42,550 INFO    : [ZigpyForwarder_18] zdp_raw_simple_descriptor_request  - [03] 0000 08 Queue Length: 3
2022-01-07 13:53:42,553 DEBUG   :Received command: ZDO.ExtRouteDisc.Rsp(Status=<Status.SUCCESS: 0>)
2022-01-07 13:53:42,555 INFO    : [ZigpyForwarder_18] sendData       - [3] RAW-COMMAND {'Profile': 0, 'Cluster': 4, 'TargetNwk': 0, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 3, 'payload': '03000008', 'AddressMode': 2} 0 Queue Length: 3
2022-01-07 13:53:42,558 DEBUG   :Sending request: ZDO.SimpleDescReq.Req(DstAddr=0x0000, NWKAddrOfInterest=0x0000, Endpoint=0)
2022-01-07 13:53:42,561 INFO    : [ZigpyForwarder_18] zdp_active_endpoint_request 0000 15
2022-01-07 13:53:42,567 INFO    : [ZigpyForwarder_18] zdp_raw_simple_descriptor_request  - [04] 0000 15 Queue Length: 4
2022-01-07 13:53:42,569 INFO    : [ZigpyForwarder_18] sendData       - [4] RAW-COMMAND {'Profile': 0, 'Cluster': 4, 'TargetNwk': 0, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 4, 'payload': '04000015', 'AddressMode': 2} 0 Queue Length: 4
2022-01-07 13:53:42,571 INFO    : [ZigpyForwarder_18] zdp_active_endpoint_request 0000 6e
2022-01-07 13:53:42,573 INFO    : [ZigpyForwarder_18] zdp_raw_simple_descriptor_request  - [05] 0000 6e Queue Length: 5
2022-01-07 13:53:42,575 DEBUG   :Received command: ZDO.SimpleDescReq.Rsp(Status=<Status.SUCCESS: 0>)
2022-01-07 13:53:42,577 INFO    : [ZigpyForwarder_18] sendData       - [5] RAW-COMMAND {'Profile': 0, 'Cluster': 4, 'TargetNwk': 0, 'TargetEp': 0, 'SrcEp': 0, 'Sqn': 5, 'payload': '0500006e', 'AddressMode': 2} 0 Queue Length: 5
2022-01-07 13:53:42,580 ERROR   :Received an exception while passing frame to API: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0xC0, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\x00\x00\x82'))
Traceback (most recent call last):
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/uart.py", line 79, in data_received
    self._api.frame_received(frame.payload)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/api.py", line 677, in frame_received
    command = command_cls.from_frame(frame, align=self.nvram.align_structs)
  File "/var/lib/domoticz/plugins/Domoticz-zigpy/zigpy_znp/types/commands.py", line 430, in from_frame
    raise ValueError(
ValueError: Frame GeneralFrame(header=CommandHeader(id=0xC0, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\x00\x00\x82') contains trailing data after parsing: b'\x00\x82'
2022-01-07 13:53:42,584 INFO    : [ZigpyForwarder_18] zdp_active_endpoint_request 0000 0a
2022-01-07 13:53:42,593 DEBUG   :Sending request: ZDO.NodeDescReq.Req(DstAddr=0x4DFF, NWKAddrOfInterest=0x4DFF)
```

**Comment by pipiche38** [comment]
```
Jan 07 13:53:22 rasp domoticz[964]: 2022-01-07 13:53:22.491  Status: Zigpy: Web backend for Web User Interface started on port: 9440
Jan 07 13:53:41 rasp domoticz[964]: 2022-01-07 13:53:41.640  Zigpy: Zigate receive message processing time Max: 3 ms with an of average: 3 ms
Jan 07 13:53:42 rasp domoticz[964]: 2022-01-07 13:53:42.170  Error: Zigpy: forwarder_thread - Error while receiving a ZiGate command
Jan 07 13:53:42 rasp domoticz[964]: 2022-01-07 13:53:42.268  Error: Zigpy: Issue in request 0180020044ff000000800400000300124b00216005420200000a0000000a025ec0200800010000000003, dumping stack: Traceback (most recent call last):
Jan 07 13:53:42 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 31, in forwarder_thread
Jan 07 13:53:42 rasp domoticz[964]:     forward_message(self, message)
Jan 07 13:53:42 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/instrumentation.py", line 13, in f_out
Jan 07 13:53:42 rasp domoticz[964]:     result = f_in(self, message)
Jan 07 13:53:42 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Classes/ZigpyTransport/forwarderThread.py", line 47, in forward_message
Jan 07 13:53:42 rasp domoticz[964]:     self.F_out(message)
Jan 07 13:53:42 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/plugin.py", line 743, in processFrame
Jan 07 13:53:42 rasp domoticz[964]:     ZigateRead(self, Devices, Data)
Jan 07 13:53:42 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 178, in ZigateRead
Jan 07 13:53:42 rasp domoticz[964]:     _decoding(self, Devices, MsgData, MsgLQI)
Jan 07 13:53:42 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/input.py", line 1910, in Decode8043
Jan 07 13:53:42 rasp domoticz[964]:     receiveZigateEpDescriptor(self, MsgData)
Jan 07 13:53:42 rasp domoticz[964]:   File "/var/lib/domoticz/plugins/Domoticz-zigpy/Modules/zigate.py", line 69, in receiveZigateEpDescriptor
Jan 07 13:53:42 rasp domoticz[964]:     if MsgDataCluster not in self.ListOfDevices[MsgDataShAddr]["Ep"][MsgDataEp]:
Jan 07 13:53:42 rasp domoticz[964]: KeyError: '02'
Jan 07 13:53:42 rasp domoticz[964]:
```

**Comment by pipiche38** [comment]
5ca3609b to address https://github.com/zigbeefordomoticz/Domoticz-Zigbee/issues/995#issuecomment-1007386186, but still the initial issue is valid
